queue:
  name: Hosted VS2017
  demands:
    - npm
    - azureps
trigger:
- master

variables:
  StorageAccount: 'dddmelbournedeployments'
  StorageContainer: 'dddmelbourne-website'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.16.x'

  - task: DeleteFiles@1
    inputs:
      Contents: '.next/**/*.*'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: Install Yarn

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: Install npm packages for app build (production)
    inputs:
      ProductionMode: true

  - task: CopyFiles@2
    displayName: Copy deployment packages to artifacts staging directory
    inputs:
      Contents: 'node_modules/**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: Install npm packages for app build

  - task: Npm@1
    displayName: Lint
    inputs:
      command: custom
      verbose: false
      customCommand: 'run lint'

  - task: Npm@1
    displayName: Build
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'

  - task: CopyFiles@2
    displayName: Copy build files to artifacts staging directory
    inputs:
      Contents: |
        .next/**/*
        static/**/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CopyFiles@2
    displayName: Copy deploy files to artifacts staging directory
    inputs:
      SourceFolder: deploy
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)\$(Build.BuildNumber).zip'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: AzureFileCopy@3
    displayName: Copy deployment to blob storage
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)\'
      azureSubscription: 'DDD Melbourne ( 7f2f0c93-1b04-4cce-8e0c-cd545ee3dfb0 )'
      Destination: AzureBlob
      storage: '$(StorageAccount)'
      ContainerName: '$(StorageContainer)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
